image:
  name: ghcr.io/peaceiris/mkdocs-material:v3.5.3

pages:
  script:
    - mkdocs build --config-file ./mkdocs-sample.yml
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main
