backend:
  name: git-gateway
  branch: dev
media_folder: "assets/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "government"
    label: "Government Resources"
    folder: "blazed_city/government"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Document ID", name: "index", widget: "number"}
      - {label: "Resource Type", name: "type", widget: "hidden", default: "law"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "market"
    label: "Trading Market"
    folder: "blazed_city/market"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "docs"
    label: "Documentation"
    folder: "blazed_city/docs"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}