backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "government"
    label: "Government Resources"
    folder: "blazed_city/government"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Document ID", name: "index", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}